### ISSUE TITLE
Improve the runtime/performance of the scripts

### ISSUE THREAD

**Issue by wandadk** [RETURN-project/BenchmarkRecovery#11]
The code for eg calculating recovery indicators is currently slow and the code should be improved and/or run in parallel.

**Comment by wandadk** [comment]
There are a few options to decrease the compute time. These are all related to the breakpoints function in strucchange (= currently main bottleneck).
- use the development branch of the bfast and strucchange package to allow for increased performance (https://github.com/bfast2/bfast/tree/dev and https://github.com/bfast2/strucchange/blob/devel/R/breakpoints.R) We can set the option to 'fast' here.
- use parallel computing (not hpc option in breakpoints function, but at a higher level) using STARS (for raster analyses) or the pbapply package

**Comment by wandadk** [comment]
I changed the code using the development branch of the bfast and strucchange package and this reduced the computation time of the breakpoints function by a factor of approx 15 times already. The code is not pushed to github yet and I'm not sure how to elegantly integrate this into the package structure. Do you know if you can specify somewhere that the package relies on a specific branch on github and not the default library?

**Comment by PabRod** [comment]
The ideal way of specifying this would be to have the changes in `bfast` updated in CRAN, and just call the appropriate version(s) from the `DESCRIPTION`. That is, not involving GitHub at all. Provided we have the developer of `bfast` in our team (cc @verbe039), this is a realistic possibility, although I don't know how much time/work will that take.

If this is not feasible, another possibility is to use Git submodules. This is basically a reference to the commit in another repository that we advise to use. I am not sure if the package will be so easy to install after this change, if applied. I used this feature some time ago, and I can research a bit about what is the best way to implement them.

**Comment by wandadk** [comment]
I was just reading about [Packrat](https://rstudio.github.io/packrat/). Could this maybe solve the problem?

**Comment by PabRod** [comment]
I've never used Packrat, but it has been in my reading list for a while. I'll try to take a look at it next week.

**Comment by wandadk** [comment]
Ok, great and thanks! I think that I can also try to put all functionality that is specific to the development branch in the vignettes and put a github install call in the beginning of the vignette. This might also solve the problem, since the R function files are not dependent anymore on the github version, right? It is not the most beautiful solution though :-).

**Comment by wandadk** [comment]
> 
> 
> Ok, great and thanks! I think that I can also try to put all functionality that is specific to the development branch in the vignettes and put a github install call in the beginning of the vignette. This might also solve the problem, since the R function files are not dependent anymore on the github version, right? It is not the most beautiful solution though :-).

Ok, that didn't work out since bfast is already loaded by benchmarkRecovery, so it can not be unloaded.

**Comment by PabRod** [comment]
Just scanned over it, but this looks promising:

https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html

**Comment by wandadk** [comment]
Thanks, looks promising indeed! I'll try it!

**Comment by wandadk** [comment]
> 
> 
> Just scanned over it, but this looks promising:
> 
> https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html

Thanks, this fixed the issue!
