### ISSUE TITLE
Structure of scripts and functions

### ISSUE THREAD

**Issue by wandadk** [RETURN-project/BenchmarkRecovery#12]
Consider to convert the set of scripts (eg bench_characterise, bench_simulate, ...) into functions and write a main script that calls these functions. This might help to understand the workflow for an outsider and potentially allow to test the code in these scripts. 

An alternative structure would be to merge all scripts and simulate time series, calculate recovery and their performance in a set of for loops. This would require a relatively large code change.

**Comment by PabRod** [comment]
We can discuss the overall structure of the project in our next meeting.

A first step will be the following:
1. No `.Rmd` files in `./R`. We have to move them to `./vignettes`
2. No (important) function definitions inside the tests, scripts nor `Rmd` files. Functions should be defined in `.R` files in the `./R` folder, and be called by everyone (tests, Rmds and scripts).

Regarding outsiders, I have to say that this project is already above average regarding clarity. This is already going in a very good direction :)

**Comment by PabRod** [comment]
Although this can **always** be improved, the current structure is already more than decent.
