### ISSUE TITLE
Problems with toydata

### ISSUE THREAD

**Issue by PabRod** [RETURN-project/BenchmarkRecovery#24]
The chunk identified as `"toydata"` in `R/data.R` is causing problems. 

Particularly, when a check is launched locally (this can be done via the build menu, or with `Ctrl + Shift + E`, or running `devtools::check()`), the following error pops:

```
Error: 'toyset' is not an exported object from 'namespace:BenchmarkRecovery'
```

Provided this seems to be just a documentation file (is this right, @wandadk?), I will comment the very last line in `R/data.R` containing `"toyset"`.

**Comment by wandadk** [comment]
Yes, I added this code chunk to document the toyset data. I'm not sure why it is causing problems. If I remember well, all data added to the data folder had to be documented in a data.R file.

**Comment by PabRod** [comment]
I see. Thanks! Believe it or not, it is the first time I use a homebrew R package for dealing with external data. 

I've found [this](https://kbroman.org/pkg_primer/pages/data.html) reference dealing with the issue. Please let me know if you a better one.

**Comment by PabRod** [comment]
Part of the problem seems to be that the standard name for data folders is `data` instead of `Data`. Even after changing that, a new error pops out:

```
file ‘toyset.rda’ has magic number 'RDX3'
```

I've created the branch [fix/toyset](https://github.com/RETURN-project/BenchmarkRecovery/tree/fix/toyset) to deal with this.

**Comment by wandadk** [comment]
Ok, thanks a lot! I will have a closer look at it as well.

**Comment by PabRod** [comment]
Check the error after this commit:

a984d94bffdc3df9e95262d47161d33f36befbc4

The problem seems to be something strange about the format of `toyset.rda`. I am unable to load it even from the console:

```
> load("~/code/github/return/BenchmarkRecovery/data/toyset.rda")

Error in load("~/code/github/return/BenchmarkRecovery/data/toyset.rda") : 
  bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning message:
file ‘toyset.rda’ has magic number 'RDX3'
  Use of save versions prior to 2 is deprecated 
```

I've got similar errors trying to load with `source` and `readRDS`. Are you experiencing this same problem?

**Comment by wandadk** [comment]
Hmmm, strange indeed. The data is loading fine on my laptop (R version 3.6.1 (2019-07-05)). Which version of R are you using?

**Comment by PabRod** [comment]
That seems to be the issue. Thanks!

``` 
─ Session info ─
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 os       Ubuntu 18.04.4 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Amsterdam            
 date     2020-03-23    
```

**Comment by wandadk** [comment]
Ok, great!
