### ISSUE TITLE
Integrate the 'realistic' decay function in the simulation scripts

### ISSUE THREAD

**Issue by wandadk** [RETURN-project/BenchmarkRecovery#27]
This includes:

- adjust the functions, so they accept another decay function
- splitting the measurement errors and the unexpected dynamics of the remainder term (needed as input for the decay function)

**Comment by PabRod** [comment]
The second point, _splitting the measurement errors and the unexpected dynamics of the remainder term (needed as input for the decay function)_, can be achieved by:

1. Running `realistic` with unexpected dynamics and perfect measurement (that is, `noise = 0` and `sigma > 0`).
2. Adding the measurement errors afterwise (just adding a vector of white noise of the same size, as we now do inside the functions).

**Comment by PabRod** [comment]
Simplified `realistic` by removing built-in measurement errors (7dc29fcde05bb45a9a4dbbdb99cd4a6c5254d9ce).

Awaiting for pull request approval.
