### ISSUE TITLE
Running the sensitivity analysis in parallel causes problems

### ISSUE THREAD

**Issue by wandadk** [RETURN-project/BenchmarkRecovery#38]
The following line of code throws an error on my laptop:

https://github.com/RETURN-project/BenchmarkRecovery/blob/1890b926b73fd0c308d8ea8f511326eed89ff672/vignettes/sensitivity_analysis.Rmd#L247

It is running fine after modifying it to sequential code.

**Comment by PabRod** [comment]
This vignette has been temporarily blacklisted from build, until we figure out why is it failing.

So, let's not forget to:

- [ ] Remove `vignettes/sensitivity_analysis.Rmd` from `.Rbuildignore`.

Related to #40.

**Comment by PabRod** [comment]
Related and potentially definitive solution

ff6a073
