### ISSUE TITLE
Add test for evalParam function

### ISSUE THREAD

**Issue by wandadk** [RETURN-project/BenchmarkRecovery#43]
Add some tests for the evalParam function : https://github.com/RETURN-project/BenchmarkRecovery/blob/30252f5c17f26e2ae776b21a1b3c6343bb19fb21/R/fun_recovery.R#L160

**Comment by PabRod** [comment]
Just to let you know, I am trying this, so to say, 0th order / brute force approach:

1. Run all the chunks of `vignettes/sensitivity_analysis.Rmd` **before** the first call to `evalParam`.
2. Store the environment as test data (~ 1 Mb) (`controlledInput.RData`).
3. Set a random seed, and run the next vignette chunk.
4. Store the output as test data (`expectedOutput.RData`).
5. Write a test that checks that, after my changes in `evalParam`, it keeps producing **the same** expected output when fed with the same controlled input.

Of course, expertise-based tests are very welcome and indeed more correct.

**Comment by wandadk** [comment]
ok, good! I'll make sure that the function returns a value and can maybe also add a more formal test.

**Comment by PabRod** [comment]
Most lines of `evalParam` are now visited by the tests. Although tests can always be improved, we can now consider this issue addressed. Thanks @wandadk!
