### ISSUE TITLE
Refactor evalParam

### ISSUE THREAD

**Issue by PabRod** [RETURN-project/BenchmarkRecovery#44]
Currently, the function `evalParam` (available at `R/fun_recovery.R`) has a couple of problems worth solving:

## Problem 1
The function is performing too many steps simultaneously. Ideally, the function usage should be:

```
values_R80P_MAPE_missVal <- evalParam(..., 'R80p', 'MAPE', 'missVal')
```

If we want to loop across different possible metrics, it is, in my opinion, better to do the loop outside the function than inside of it.

Related: `simulCase` at `R/ts_generator.R`

## Problem 2
The function is saving its results instead of passing them as an output.

## Note
Unfortunately, the function lacks tests. We are working on that simultaneously (issue #43).

**Comment by PabRod** [comment]
I've uploaded a detailed [vignette](https://github.com/RETURN-project/BenchmarkRecovery/blob/fix/refactor_evalParam/vignettes/using_apply.Rmd) with the ideas I want to apply and an indication of how to do so (I needed to refresh my mind about `apply` functions, hehe).

A quick graphical summary is this:

Now we are doing this:

![](https://raw.githubusercontent.com/RETURN-project/BenchmarkRecovery/fix/refactor_evalParam/img/diagram_now.png)

and I think it will be smart to do this instead:

![](https://raw.githubusercontent.com/RETURN-project/BenchmarkRecovery/fix/refactor_evalParam/img/diagram_future.png)

My main motivation is the clear 3D matrix structure of the saved files. 

Do you think this is feasible, @wandadk? Can you foresee a problem with this approach?

**Comment by wandadk** [comment]
Thanks Pablo,

I'll check this tomorrow in detail!

**Comment by wandadk** [comment]
Hi Pablo,

Thanks for the great vignette that explains your idea to refactor the evalParam function. I think it is a good idea and don't see any problems immediately. There is only one thing that I'm not sure of. One of the evaluation parameters is the 'nTS' parameter value, which gives the number of simulated time series that didn't produce a NA result. Other evaluation parameters are R2 and RMSE. I wonder if showing the nTS and RMSE parameter in one graph makes sense if they do not originate from the same time series. But maybe that doesn't matter if we just simulate enough time series (so our results are robust).

**Comment by wandadk** [comment]
I noticed that some of the documentation is outdated or incomplete. I'll update it tomorrow.

**Comment by PabRod** [comment]
The commit ba72d30 may require an explanation. I've encapsulated several chunks into one function (preliminary name: `extract_settings`). This was brute-force encapsulation: I've just copied the chunks inside a function body with minimal edits. 

The reason: this encapsulation will be very helpful in the near future, when we'll pass a set of filenames to be processed in parallel instead of only one.

This action have some **minor** consequences worth mentioning. It:

- May have affected the narrative of the text in the `sensitivity_analysis` vignette (in those points where the text referred to code, now missing).
- Forced me to hard-code some variables in the chunk labelled as `plot`.
- May be a good idea to fine-tune this function and move it to the `R` folder.

**Comment by PabRod** [comment]
Commit (253590c) adds parallelized multifile capability.

- What changed: now, a list of files can be executed in parallel. 
- Why is it relevant: if the number of files to be analyzed is the main bottleneck, this is the crucial parallelization step.

**Comment by PabRod** [comment]
Although `evalParam` can be further refactored (and thus, allows even more parallelization), I consider this task reached no less than its minimum goal.
