### ISSUE TITLE
Bug in intertwinning vignette - code

### ISSUE THREAD

**Issue by PabRod** [RETURN-project/BenchmarkRecovery#45]
The vignette `sensitivity_analysis` suddenly hits the error: 

```
calcBFASTrec(tsi, obspyr, h, shortDenseTS, nPre, nDist, nPostMin, : 
No seasonal term allowed for time series with one observation per year or less.
```

Perhaps I've been building from a previous version of the package. I've couldn't figure out what's wrong by navigating the history. Asking @wandadk and hot-fixing the issue seems a better idea.

Related to #44 and #38.

**Comment by PabRod** [comment]
The error was introduced in commit c0e2dcbfe0a4790097f07e015c85ebff55fd718d, and the problem remained unnoticed due to the fact that:

- `vignettes/sensitivity_analysis.Rmd` is excluded from build.
- The interactive tests were performed without re-installing `BenchmarkRecovery`, that is, using a version previous to the problematic commit.

**Comment by wandadk** [comment]
I'll check the bug now!

**Comment by PabRod** [comment]
No need to do so @wandadk, I just got it!

I am testing and will push soon.
