### ISSUE TITLE
The sensitivity results for the disturbance magnitude ('distMag') are lacking 

### ISSUE THREAD

**Issue by wandadk** [RETURN-project/BenchmarkRecovery#47]
When running the sensitivity analysis for 10000 time series per evaluated parameter setting on Spider, the results for the disturbance magnitude were not produced. The vignette did not produce any error (besides in the plotting part, since one of the inputs is lacking). All inputs and results are available on Spider in _/project/return/Data/BenchmarkRecovery/Run_20200930_

I am trying to run the vignette again in Spider (_/project/return/Data/BenchmarkRecovery/Run_20200930_Lin_distMag_). Here, I am only generating results for the disturbance magnitude parameter. Let's see if this problem is persistent.

**Comment by PabRod** [comment]
This was not really a bug. It was related with the time given to the computation.
