### ISSUE TITLE
Error SDE simulation time series

### ISSUE THREAD

**Issue by wandadk** [RETURN-project/BenchmarkRecovery#50]
The following code leads to an error:

```
## Set the times
ts <- seq(1, 120, by = 1)

## Set the parameters 
offset <- 0
pert <- 5
tpert <- 15
thalf <- 3
noise <- 0.1

ys_r <- realistic(ts, offset, pert, tpert, thalf, noise)
```

error message: 
```
Error in ts(realistic(tfill, noise = noise), start = t[1], end = t[i -  : 
  'end' must be a whole number of cycles after 'start'
Called from: ts(realistic(tfill, noise = noise), start = t[1], end = t[i - 
    1], frequency = frequency(sol))
```

This could maybe be solved by fixing the frequency of the time series objects. In this case the frequency of `sol` should be 1, but the frequency  equals 0.9916667. If `N = length(t)` in the `sde.sim` function, the frequency is correct, but `sol` contains one observation too many (so should be cropped).

**Comment by wandadk** [comment]
@PabRod can you maybe give some feedback on this? Thanks!

**Comment by PabRod** [comment]
This should fix it @wandadk. Thanks for notifying!

**Comment by wandadk** [comment]
Thanks @PabRod for the fast help! It solves the error, but now the disturbance is not taking place at the correct date. Using the example above, I get a perturbation at time 16 and not 15.

**Comment by PabRod** [comment]
I see. I'll take a second look.

**Comment by PabRod** [comment]
@wandadk 
Quick patch: start your times at 0.

I am working on a more robust solution.

**Comment by PabRod** [comment]
I think it is now fixed @wandadk. Let me know if you experience any further problem.

**Comment by wandadk** [comment]
Thanks a lot @PabRod! This seems to fix the issue indeed :).
